
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REL_OP = 8;
  public static final int STRING_TEXT = 36;
  public static final int INCREMENT = 3;
  public static final int SHIFTRIGHT = 34;
  public static final int CONST = 2;
  public static final int SLASH = 14;
  public static final int CASE = 16;
  public static final int OR_OPR = 25;
  public static final int CLOSE_SQUARE = 40;
  public static final int DECREMENT = 46;
  public static final int SINGLE_AND = 35;
  public static final int FOR = 18;
  public static final int MINUS = 29;
  public static final int TYPE = 12;
  public static final int OPEN_PARAN = 39;
  public static final int ASTRISK = 31;
  public static final int COMMA = 11;
  public static final int OPEN_SQUARE = 37;
  public static final int OPEN_CURLY = 38;
  public static final int PLUS = 28;
  public static final int IF = 5;
  public static final int DOT = 10;
  public static final int AND_OP = 26;
  public static final int DOTS = 27;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 22;
  public static final int error = 1;
  public static final int INFER = 45;
  public static final int PERCENT = 32;
  public static final int SEMI_COLON = 48;
  public static final int BREAK = 47;
  public static final int CLOSE_PARAN = 42;
  public static final int SWITCH = 15;
  public static final int IMPORT = 21;
  public static final int COLON = 23;
  public static final int CLOSE_CURLY = 41;
  public static final int ELSE = 7;
  public static final int FUNC = 43;
  public static final int PACKAGE = 20;
  public static final int DEFAULT = 17;
  public static final int SHIFTLEFT = 33;
  public static final int SINGLE_OR = 30;
  public static final int EXLIM = 44;
  public static final int STRUCT = 19;
  public static final int INT_LIT = 13;
  public static final int VAR = 4;
  public static final int COLON_EQUAL = 6;
  public static final int IDENTIFIER = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONST",
  "INCREMENT",
  "VAR",
  "IF",
  "COLON_EQUAL",
  "ELSE",
  "REL_OP",
  "RETURN",
  "DOT",
  "COMMA",
  "TYPE",
  "INT_LIT",
  "SLASH",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "FOR",
  "STRUCT",
  "PACKAGE",
  "IMPORT",
  "EQUAL",
  "COLON",
  "IDENTIFIER",
  "OR_OPR",
  "AND_OP",
  "DOTS",
  "PLUS",
  "MINUS",
  "SINGLE_OR",
  "ASTRISK",
  "PERCENT",
  "SHIFTLEFT",
  "SHIFTRIGHT",
  "SINGLE_AND",
  "STRING_TEXT",
  "OPEN_SQUARE",
  "OPEN_CURLY",
  "OPEN_PARAN",
  "CLOSE_SQUARE",
  "CLOSE_CURLY",
  "CLOSE_PARAN",
  "FUNC",
  "EXLIM",
  "INFER",
  "DECREMENT",
  "BREAK",
  "SEMI_COLON"
  };
}

