
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REL_OP = 9;
  public static final int DIVIDE = 33;
  public static final int STRING_TEXT = 38;
  public static final int SHIFTRIGHT = 36;
  public static final int INCREMENT = 3;
  public static final int CONST = 2;
  public static final int SLASH = 15;
  public static final int COMMENT = 8;
  public static final int CASE = 17;
  public static final int SMALLER = 52;
  public static final int GREATER = 53;
  public static final int OR_OPR = 26;
  public static final int CLOSE_SQUARE = 42;
  public static final int DECREMENT = 49;
  public static final int SINGLE_AND = 37;
  public static final int FOR = 19;
  public static final int MINUS = 30;
  public static final int TYPE = 13;
  public static final int OPEN_PARAN = 41;
  public static final int ASTRISK = 32;
  public static final int COMMA = 12;
  public static final int LESS_EQUAL = 55;
  public static final int OPEN_SQUARE = 39;
  public static final int OPEN_CURLY = 40;
  public static final int PLUS = 29;
  public static final int IF = 5;
  public static final int DOT = 11;
  public static final int AND_OP = 27;
  public static final int DOTS = 28;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 23;
  public static final int GREATER_EQUAL = 51;
  public static final int error = 1;
  public static final int INFER = 47;
  public static final int PERCENT = 34;
  public static final int SEMI_COLON = 56;
  public static final int BREAK = 50;
  public static final int CLOSE_PARAN = 44;
  public static final int SWITCH = 16;
  public static final int IMPORT = 22;
  public static final int COLON = 24;
  public static final int CLOSE_CURLY = 43;
  public static final int ELSE = 7;
  public static final int FUNC = 45;
  public static final int Const = 48;
  public static final int PACKAGE = 21;
  public static final int SHIFTLEFT = 35;
  public static final int DEFAULT = 18;
  public static final int SINGLE_OR = 31;
  public static final int EXLIM = 46;
  public static final int STRUCT = 20;
  public static final int INT_LIT = 14;
  public static final int VAR = 4;
  public static final int COLON_EQUAL = 6;
  public static final int EQUAL_EQUAL = 54;
  public static final int IDENTIFIER = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONST",
  "INCREMENT",
  "VAR",
  "IF",
  "COLON_EQUAL",
  "ELSE",
  "COMMENT",
  "REL_OP",
  "RETURN",
  "DOT",
  "COMMA",
  "TYPE",
  "INT_LIT",
  "SLASH",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "FOR",
  "STRUCT",
  "PACKAGE",
  "IMPORT",
  "EQUAL",
  "COLON",
  "IDENTIFIER",
  "OR_OPR",
  "AND_OP",
  "DOTS",
  "PLUS",
  "MINUS",
  "SINGLE_OR",
  "ASTRISK",
  "DIVIDE",
  "PERCENT",
  "SHIFTLEFT",
  "SHIFTRIGHT",
  "SINGLE_AND",
  "STRING_TEXT",
  "OPEN_SQUARE",
  "OPEN_CURLY",
  "OPEN_PARAN",
  "CLOSE_SQUARE",
  "CLOSE_CURLY",
  "CLOSE_PARAN",
  "FUNC",
  "EXLIM",
  "INFER",
  "Const",
  "DECREMENT",
  "BREAK",
  "GREATER_EQUAL",
  "SMALLER",
  "GREATER",
  "EQUAL_EQUAL",
  "LESS_EQUAL",
  "SEMI_COLON"
  };
}

